use crate::ginseng::{Piece, PlayerID};

pub const STARTING_BOARD: [[Option<Piece>; 17]; 17] = [
    [
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        None,
        None,
        None,
        None,
        Some(Piece::Lotus {
            player: PlayerID::Guest,
        }),
        None,
        None,
        None,
        None,
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
    ],
    [
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        None,
        None,
        None,
        None,
        Some(Piece::Dragon {
            player: PlayerID::Guest,
        }),
        None,
        Some(Piece::BadgerMole {
            player: PlayerID::Guest,
        }),
        None,
        None,
        None,
        None,
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
    ],
    [
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        None,
        None,
        None,
        None,
        Some(Piece::SkyBison {
            player: PlayerID::Guest,
        }),
        None,
        None,
        None,
        Some(Piece::Koi {
            player: PlayerID::Guest,
        }),
        None,
        None,
        None,
        None,
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
    ],
    [
        Some(Piece::OutOfBounds),
        None,
        None,
        None,
        None,
        Some(Piece::Wheel {
            player: PlayerID::Guest,
        }),
        None,
        None,
        None,
        None,
        None,
        Some(Piece::Wheel {
            player: PlayerID::Guest,
        }),
        None,
        None,
        None,
        None,
        Some(Piece::OutOfBounds),
    ],
    [
        None,
        None,
        None,
        Some(Piece::Orchid {
            player: PlayerID::Guest,
        }),
        Some(Piece::Ginseng {
            player: PlayerID::Guest,
        }),
        None,
        None,
        None,
        Some(Piece::LionTurtle {
            player: PlayerID::Guest,
        }),
        None,
        None,
        None,
        Some(Piece::Ginseng {
            player: PlayerID::Guest,
        }),
        Some(Piece::Orchid {
            player: PlayerID::Guest,
        }),
        None,
        None,
        None,
    ],
    [None; 17],
    [None; 17],
    [None; 17],
    [None; 17],
    [None; 17],
    [None; 17],
    [None; 17],
    [
        None,
        None,
        None,
        Some(Piece::Orchid {
            player: PlayerID::Host,
        }),
        Some(Piece::Ginseng {
            player: PlayerID::Host,
        }),
        None,
        None,
        None,
        Some(Piece::LionTurtle {
            player: PlayerID::Host,
        }),
        None,
        None,
        None,
        Some(Piece::Ginseng {
            player: PlayerID::Host,
        }),
        Some(Piece::Orchid {
            player: PlayerID::Host,
        }),
        None,
        None,
        None,
    ],
    [
        Some(Piece::OutOfBounds),
        None,
        None,
        None,
        None,
        Some(Piece::Wheel {
            player: PlayerID::Host,
        }),
        None,
        None,
        None,
        None,
        None,
        Some(Piece::Wheel {
            player: PlayerID::Host,
        }),
        None,
        None,
        None,
        None,
        Some(Piece::OutOfBounds),
    ],
    [
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        None,
        None,
        None,
        None,
        Some(Piece::Koi {
            player: PlayerID::Host,
        }),
        None,
        None,
        None,
        Some(Piece::SkyBison {
            player: PlayerID::Host,
        }),
        None,
        None,
        None,
        None,
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
    ],
    [
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        None,
        None,
        None,
        None,
        Some(Piece::BadgerMole {
            player: PlayerID::Host,
        }),
        None,
        Some(Piece::Dragon {
            player: PlayerID::Host,
        }),
        None,
        None,
        None,
        None,
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
    ],
    [
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        None,
        None,
        None,
        None,
        Some(Piece::Lotus {
            player: PlayerID::Host,
        }),
        None,
        None,
        None,
        None,
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
        Some(Piece::OutOfBounds),
    ],
];
